#!/usr/bin/env bash
#
# Generates starter.epd from a curated list of opening move sequences.
# Uses the bundled ./stockfish binary (at the repo root) to convert UCI move
# lists into correct FENs.
#
# Run from the repo root:
#   bash tests/sprt/book/generate_starter.sh
#
# To add more positions, append "Name|move1 move2 ..." lines to the
# OPENINGS heredoc below. Moves are in UCI coordinate notation.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
SF="$REPO_ROOT/stockfish"
OUT="$REPO_ROOT/tests/sprt/book/starter.epd"

if [ ! -x "$SF" ]; then
    echo "error: $SF not found or not executable" >&2
    exit 1
fi

OPENINGS=$(cat <<'EOF'
Open Game|e2e4 e7e5
Sicilian|e2e4 c7c5
French|e2e4 e7e6
Caro-Kann|e2e4 c7c6
Pirc|e2e4 d7d6
Alekhine|e2e4 g8f6
Modern|e2e4 g7g6
Scandinavian|e2e4 d7d5
Nimzowitsch|e2e4 b8c6
QG Declined|d2d4 d7d5
Indian Defense|d2d4 g8f6
Old Benoni|d2d4 c7c5
Dutch|d2d4 f7f5
Queens Pawn|d2d4 d7d6
English|c2c4 e7e5
Symmetrical English|c2c4 c7c5
English Indian|c2c4 g8f6
Reti|g1f3 d7d5
Reti Symmetrical|g1f3 g8f6
King's Pawn Italian|e2e4 e7e5 g1f3 b8c6 f1c4
King's Pawn Ruy Lopez|e2e4 e7e5 g1f3 b8c6 f1b5
King's Pawn Petrov|e2e4 e7e5 g1f3 g8f6
King's Pawn Scotch|e2e4 e7e5 g1f3 b8c6 d2d4
Sicilian Open|e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4
Sicilian Najdorf setup|e2e4 c7c5 g1f3 d7d6
Sicilian Classical|e2e4 c7c5 g1f3 b8c6
Sicilian Kan|e2e4 c7c5 g1f3 e7e6
French Advance|e2e4 e7e6 d2d4 d7d5 e4e5
French Tarrasch|e2e4 e7e6 d2d4 d7d5 b1d2
French Classical|e2e4 e7e6 d2d4 d7d5 b1c3
Caro-Kann Main|e2e4 c7c6 d2d4 d7d5 b1c3
Caro-Kann Exchange|e2e4 c7c6 d2d4 d7d5 e4d5 c6d5
QG Slav|d2d4 d7d5 c2c4 c7c6
QG Accepted|d2d4 d7d5 c2c4 d5c4
QG Orthodox|d2d4 d7d5 c2c4 e7e6
Kings Indian Defense|d2d4 g8f6 c2c4 g7g6
Nimzo-Indian|d2d4 g8f6 c2c4 e7e6 b1c3 f8b4
Queens Indian|d2d4 g8f6 c2c4 e7e6 g1f3 b7b6
Grunfeld|d2d4 g8f6 c2c4 g7g6 b1c3 d7d5
Benko|d2d4 g8f6 c2c4 c7c5 d4d5 b7b5
EOF
)

echo "# Starter opening book for capizero SPRT testing." > "$OUT"
echo "# Generated by tests/sprt/book/generate_starter.sh" >> "$OUT"
echo "# Format: EPD (one position per line), c0 op holds opening name." >> "$OUT"
echo "" >> "$OUT"

count=0
while IFS='|' read -r name moves; do
    [ -z "$name" ] && continue
    [ "${name:0:1}" = "#" ] && continue

    fen=$(printf 'uci\nposition startpos moves %s\nd\nquit\n' "$moves" \
        | "$SF" 2>/dev/null \
        | awk -F'Fen: ' '/^Fen: /{print $2; exit}')

    if [ -z "$fen" ]; then
        echo "warn: could not generate FEN for: $name ($moves)" >&2
        continue
    fi

    # EPD format: strip halfmove/fullmove (last two fields), append c0 op.
    epd=$(echo "$fen" | awk '{printf "%s %s %s %s %s", $1, $2, $3, $4, ""}')
    echo "${epd% } c0 \"$name\";" >> "$OUT"
    count=$((count + 1))
done <<< "$OPENINGS"

echo "Generated $count positions -> $OUT"
